# Generated by Django 2.2.12 on 2020-06-01 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('documento', models.BigIntegerField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('telefonePrincipal', models.CharField(blank=True, max_length=15, null=True)),
                ('telefoneSecundario', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('telefonePrincipal', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=3)),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=9)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9)),
                ('situacao', models.CharField(choices=[('P', 'Previsto'), ('R', 'Realizado')], default='P', max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacao.Cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacao.Produto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacao.Unidade')),
            ],
            options={
                'ordering': ['data', 'produto'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notafiscal', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=9)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9)),
                ('situacao', models.CharField(choices=[('P', 'Previsto'), ('R', 'Realizado')], default='P', max_length=1)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacao.Fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacao.Produto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacao.Unidade')),
            ],
            options={
                'ordering': ['data', 'produto'],
            },
        ),
    ]
