# Generated by Django 2.2.12 on 2020-05-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefonePrincipal',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefoneSecundario',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
