# Generated by Django 2.2.12 on 2020-06-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='unidade',
        ),
        migrations.AddField(
            model_name='compra',
            name='numeroPedido',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='produto',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Unidade',
        ),
    ]
