# Generated by Django 2.2.12 on 2020-05-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0002_auto_20200528_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['data', 'produto']},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='unidade',
            options={'ordering': ['descricao']},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['data', 'produto']},
        ),
        migrations.AlterField(
            model_name='compra',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefonePrincipal',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateField(),
        ),
    ]
